#!/bin/bash
# Get the filename from the environment variable
pyfile="$PYFILE"

python3 -m py_compile "$pyfile"
compiled_file="${pyfile}c"
echo "Compiling '$pyfile' ..."
mv ./__pycache__/*.pyc ./$compiled_file
